env:
  global:
    - NODE_ENV=test
language: node_js
node_js:
  - "node"
install: npm install
services:
  - postgresql
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
  - npm run pretest

script: npm test

notifications:
  email: true
