env:
  global:
    - NODE_ENV=test
language: node_js
node_js:
  - "node"
install: npm install
services:
  - postgresql
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database insight_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
  - npx knex migrate:down --env=testing
  - npx knex migrate:latest --env=testing

script: npm run test

notifications:
  email: true
